# Out-of-tree Linux OFS filesystem module.
# OFS is maintained as an independent filesystem implementation.

obj-m += ofs.o
ofs-y := canonical.o super.o namei.o inode.o file.o dir.o amigaffs.o bitmap.o symlink.o
