#
# Out-of-tree Linux OFS filesystem module.
# Based on the pinned Linux v6.12.107 fs/affs implementation while OFS and FFS
# are separated into independent filesystem modules.
#

obj-m += ofs.o
ofs-y := canonical.o super.o namei.o inode.o file.o dir.o amigaffs.o bitmap.o symlink.o
