#!/bin/sh
# SPDX-License-Identifier: GPL-3.0-or-later
set -e
undo=no
case "$1" in
    remove|purge|abort-install|disappear) undo=yes ;;
    upgrade|abort-upgrade)
        if dpkg --compare-versions "${2:-0}" lt 0.5.5; then undo=yes; fi
        ;;
esac
if [ "$undo" = yes ] && \
   [ "$(dpkg-divert --listpackage /usr/bin/gnome-disks)" = infiltrator-filesystem-support-udisks ]; then
    dpkg-divert --package infiltrator-filesystem-support-udisks \
        --remove --rename --divert /usr/bin/gnome-disks.filesystem-support-original \
        /usr/bin/gnome-disks
fi
