# Out-of-tree Linux FFS filesystem module.
# FFS is maintained as an independent filesystem implementation.

obj-m += ffs.o
ffs-y := canonical.o super.o namei.o inode.o file.o dir.o amigaffs.o bitmap.o symlink.o
